
name: Build-joplin

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # - uses: actions/checkout@v4

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1

      - name: Install Linux dependencies
        run: |
            sudo apt-get update || true
            sudo apt-get install -y libsecret-1-dev


      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Checkout Source Code
        run: |
            git clone  https://github.com/AoThen/joplin joplin-android
            mv -f joplin-android/* ./
            rm -rf joplin-android
          
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
        

      - name: Install Yarn
        run: |
          corepack enable

      - name: Install
        run:  yarn install
        env:
          SKIP_ONENOTE_CONVERTER_BUILD: 1
      
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true


      - name: Decode Keystore
        run: |
          cd packages/app-mobile/android
      
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          echo "storeFile=${{ github.workspace }}packages/app-mobile/android/kt.jks" >> keystore.properties

          echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 -d > kt.jksx
       

      - name: Prepare App
        run: |
          cd packages/app-mobile/android
          ./gradlew assembleRelease

          cd packages/app-mobile/android/app
          APK_FILE="./build/outputs/apk/release/app-release.apk"
          if test ! -f "$APK_FILE" ; then
            echo "APK file not found."
            exit 1
          else
            echo "APK file found at: $APK_FILE"
          fi

          mkdir -p ${{ github.workspace }}/TVBox/
          find . -name "*.apk" -exec mv {} ${{ github.workspace }}/TVBox/ \;
          
        #   for file in `find ~ \( -name "*.apk" -o -name "*java*.apk" \) -not -name "*x86*" -print`; do
        #     base=$(basename "$file")
        #     new_base="joplin-android_$base"
        #     mv "$file" "TVBox/$new_base"
        #   done

        #   ls TVBox/*.apk


      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: joplin-android
          path: ${{ github.workspace }}/TVBox/*.apk